version: "3"
services:
  beach:
    build:
      context: ./beach
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/src/lobtail/
    tty: true
    working_dir: /usr/src/lobtail/
  collector:
    build:
      context: ./lobtail-collector
      dockerfile: Dockerfile.local
    volumes:
      - ./data/:/usr/src/lobtail/data/
    tty: true
    working_dir: /usr/src/qlib/
