version: "3"
services:
  lobtail:
    build:
      context: ../lobtail
      dockerfile: ${PWD}/lobtail/Dockerfile
    volumes:
      - ../:/usr/src/lobtail
    tty: true
    working_dir: /usr/src/lobtail/lobtail
